import { create } from "zustand";

type Language = "es" | "en";

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    nav_services: "Servicios",
    nav_fleet: "Flota",
    nav_book: "Reservar Ahora",
    hero_badge: "Servicio de Taxi y Traslados Privados en Madrid",
    hero_title: "La forma más cómoda y puntual de viajar.",
    hero_desc: "Tu transporte de confianza en Madrid con precio cerrado. Viaja en vehículos amplios y confortables con la máxima puntualidad y profesionalidad garantizadas.",
    hero_btn_book: "Reservar Traslado",
    hero_btn_fleet: "Nuestra Flota",
    services_title: "Nuestros Servicios",
    services_desc: "Ofrecemos soluciones de transporte a tu medida, con precio cerrado y reserva anticipada para tu total tranquilidad.",
    service_1_title: "Aeropuertos y Estaciones",
    service_1_desc: "Traslados puntuales desde y hacia el Aeropuerto Adolfo Suárez Madrid-Barajas y estaciones de tren (Atocha, Chamartín).",
    service_2_title: "Disposición por Horas",
    service_2_desc: "Vehículo con conductor a tu disposición por horas para gestiones comerciales, eventos o turismo por la ciudad.",
    service_3_title: "Viajes Privados",
    service_3_desc: "Viajes de larga distancia a cualquier punto de España con total comodidad, espacio para el equipaje y seguridad.",
    fleet_title: "Nuestra Flota",
    fleet_desc: "Vehículos modernos, amplios y completamente equipados para garantizar un viaje excelente.",
    fleet_v_title: "Mercedes Clase V",
    fleet_v_desc: "La solución perfecta para viajar en grupo o familia. Amplio espacio y total comodidad para hasta 7 pasajeros con gran capacidad de equipaje.",
    fleet_v_pax: "Hasta 7 Pax",
    fleet_v_tag: "Monovolumen Amplio",
    fleet_s_title: "Berlinas Ejecutivas",
    fleet_s_desc: "Vehículos confortables e impecables para traslados particulares, ejecutivos o de empresa. Profesionalidad para tus trayectos de hasta 4 ocupantes.",
    fleet_s_pax: "Hasta 4 Pax",
    fleet_s_tag: "Clase Confort",
    booking_badge: "Garantía de Servicio",
    booking_title: "Reserve su traslado con anticipación",
    booking_desc: "Conozca el precio exacto antes de viajar. Sin tarifas ocultas, sin taxímetros. Disfrute de la tranquilidad de tener su coche esperándole puntualmente.",
    booking_feature_1: "Precio cerrado y garantizado",
    booking_feature_2: "Cancelación gratuita hasta 24h antes",
    booking_feature_3: "Tiempo de espera de cortesía incluido",
    booking_feature_4: "Atención al cliente 24/7",
    booking_payments: "Pagos 100% Seguros",
    form_title: "Solicitar Presupuesto",
    form_desc: "Complete los detalles de su viaje y le garantizaremos un precio cerrado sin sorpresas.",
    form_origin: "Origen",
    form_origin_placeholder: "Aeropuerto, Hotel, Dirección...",
    form_destination: "Destino",
    form_destination_placeholder: "Destino final...",
    form_date: "Fecha",
    form_time: "Hora",
    form_passengers: "Pasajeros",
    form_luggage: "Equipaje",
    form_flight: "Número de vuelo / tren",
    form_flight_placeholder: "Ej: IB3456, AVE 02231...",
    form_extras: "Accesorios para niños",
    form_extras_none: "No necesito",
    form_extras_baby: "Silla de bebé",
    form_extras_booster: "Alzador",
    form_extras_both: "Silla de bebé + Alzador",
    form_comments: "Comentarios o indicaciones",
    form_comments_placeholder: "Cualquier indicación especial para el conductor...",
    form_submit: "Solicitar Reserva",
    form_processing: "Procesando...",
    form_success_title: "Solicitud Recibida",
    form_success_desc: "Su petición ha sido registrada correctamente. Un agente se pondrá en contacto con usted en breve para la confirmación y el pago.",
    form_success_btn: "Hacer otra reserva",
    toast_success_title: "Reserva Solicitada",
    toast_success_desc: "Nos pondremos en contacto pronto para confirmar su traslado.",
    toast_error_title: "Error en la reserva",
    whatsapp_label: "Reservar por WhatsApp",
    whatsapp_msg: "Hola! Quiero reservar un servicio",
    footer_rights: "Todos los derechos reservados.",
    footer_official: "Servicio oficial de Taxi y Traslados en la Comunidad de Madrid.",
  },
  en: {
    nav_services: "Services",
    nav_fleet: "Fleet",
    nav_book: "Book Now",
    hero_badge: "Taxi & Private Transfer Service in Madrid",
    hero_title: "The most comfortable and punctual way to travel.",
    hero_desc: "Your trusted transport in Madrid with a fixed price. Travel in spacious, comfortable vehicles with maximum punctuality and professionalism guaranteed.",
    hero_btn_book: "Book Transfer",
    hero_btn_fleet: "Our Fleet",
    services_title: "Our Services",
    services_desc: "We offer transport solutions tailored to you, with a fixed price and advance booking for your total peace of mind.",
    service_1_title: "Airports & Stations",
    service_1_desc: "Punctual transfers to and from Adolfo Suárez Madrid-Barajas Airport and train stations (Atocha, Chamartín).",
    service_2_title: "Hourly Chauffeur",
    service_2_desc: "Vehicle with driver at your disposal by the hour for business, events, or city tours.",
    service_3_title: "Private Trips",
    service_3_desc: "Long-distance journeys to any point in Spain with full comfort, luggage space, and safety.",
    fleet_title: "Our Fleet",
    fleet_desc: "Modern, spacious, and fully equipped vehicles to guarantee an excellent journey.",
    fleet_v_title: "Mercedes V-Class",
    fleet_v_desc: "The perfect solution for group or family travel. Spacious and comfortable for up to 7 passengers with large luggage capacity.",
    fleet_v_pax: "Up to 7 Pax",
    fleet_v_tag: "Spacious Minivan",
    fleet_s_title: "Executive Sedans",
    fleet_s_desc: "Comfortable and impeccable vehicles for private, executive, or corporate transfers. Professionalism for your journeys of up to 4 occupants.",
    fleet_s_pax: "Up to 4 Pax",
    fleet_s_tag: "Comfort Class",
    booking_badge: "Service Guarantee",
    booking_title: "Book your transfer in advance",
    booking_desc: "Know the exact price before traveling. No hidden fees, no meters. Enjoy the peace of mind of having your car waiting for you punctually.",
    booking_feature_1: "Fixed and guaranteed price",
    booking_feature_2: "Free cancellation up to 24h before",
    booking_feature_3: "Complimentary waiting time included",
    booking_feature_4: "24/7 customer support",
    booking_payments: "100% Secure Payments",
    form_title: "Request a Quote",
    form_desc: "Complete your trip details and we will guarantee a fixed price with no surprises.",
    form_origin: "Origin",
    form_origin_placeholder: "Airport, Hotel, Address...",
    form_destination: "Destination",
    form_destination_placeholder: "Final destination...",
    form_date: "Date",
    form_time: "Time",
    form_passengers: "Passengers",
    form_luggage: "Luggage",
    form_flight: "Flight / Train number",
    form_flight_placeholder: "E.g: IB3456, AVE 02231...",
    form_extras: "Child accessories",
    form_extras_none: "Not needed",
    form_extras_baby: "Baby seat",
    form_extras_booster: "Booster seat",
    form_extras_both: "Baby seat + Booster",
    form_comments: "Comments or instructions",
    form_comments_placeholder: "Any special instructions for the driver...",
    form_submit: "Request Booking",
    form_processing: "Processing...",
    form_success_title: "Request Received",
    form_success_desc: "Your request has been successfully registered. An agent will contact you shortly for confirmation and payment.",
    form_success_btn: "Make another booking",
    toast_success_title: "Booking Requested",
    toast_success_desc: "We will contact you soon to confirm your transfer.",
    toast_error_title: "Booking Error",
    whatsapp_label: "Book via WhatsApp",
    whatsapp_msg: "Hello! I would like to book a service",
    footer_rights: "All rights reserved.",
    footer_official: "Official Taxi and Transfer Service in the Community of Madrid.",
  },
};

export const useLanguage = create<LanguageState>((set, get) => ({
  language: "es",
  setLanguage: (lang) => set({ language: lang }),
  t: (key) => {
    const lang = get().language;
    return (translations[lang] as any)[key] || key;
  },
}));
